version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/go.mod"  
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/tektoncd/operator" 
    groups:
      go:
        patterns:
        - "github.com/tektoncd/*"
        update-types:
          - "minor"
