version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"  
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "github.com/tektoncd/operator" 
    groups:
      go:
        update-types:
          - "minor"
