version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/tektoncd/operator"
        version-resolver: "auto"
        version-requirements:
          - update-types: "minor"
